name: Auto-merge Talent Updates

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - 'master'

permissions:
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.head.ref == 'feature/update-talent-database' && github.event.pull_request.user.login == github.repository_owner

    steps:
      - name: Auto-merge PR
        run: |
          gh pr merge "${{ github.event.pull_request.number }}" --merge --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
